# Generated by Django 3.2 on 2022-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220521_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comingsoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster_path', models.TextField()),
                ('d_day', models.IntegerField()),
            ],
        ),
    ]
