# Generated by Django 3.2 on 2022-05-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_boxoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_watched',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
