# Generated by Django 3.2 on 2022-05-23 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_movie_is_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_watched',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_watched',
            field=models.ManyToManyField(related_name='watch_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
