# Generated by Django 3.2 on 2022-05-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxoffice',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
