# Generated by Django 3.2 on 2022-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_boxoffice_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxofficeTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=20)),
                ('audience', models.CharField(max_length=20)),
                ('poster_path', models.TextField()),
            ],
        ),
    ]
